# Generated by Django 5.0.1 on 2024-01-29 17:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("status", models.BooleanField(default=False)),
                (
                    "conversation",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(blank=True), size=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phoneNo", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=256)),
                ("firstName", models.CharField(max_length=200)),
                ("lastName", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("about", models.TextField()),
                ("ratingNum", models.FloatField()),
                ("rating", models.IntegerField()),
                ("image", models.URLField()),
                ("what_learn", models.TextField()),
                ("modules", models.ManyToManyField(to="ai_tutor.module")),
            ],
        ),
    ]
